### PR TITLE
Catch error thrown in fallback

### LINKED ISSUE #7: Convert thrown error into a rejected promise
When for what ever reason the fallback function throw an erro insted of returning a promise. the promise chain is broken and the error is just thrown and totaly lost by the caller.

I know that the docs state "Do something other than rejecting with an error on timeout." but som times this is not under our controlle and it wuld be nice if p-timeout wuld guard agenst this.

```js
const doIt = () =>  pTimeout(neverEnding(), 1000, () => {
  // silly internal bug
  throw new Error('I pooped my pants'); // this will just be thrown to no one.
});

### PR DESCRIPTION
**Pull request by agirorn**
This protects developers from accidentally throw an errors
inside the fallback function, they now are converted into a rejected promise.

closes #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -15,7 +16,7 @@ module.exports = (promise, ms, fallback) => new Promise((resolve, reject) => {
 
 	const timer = setTimeout(() => {
 		if (typeof fallback === 'function') {
-			resolve(fallback());
+			resolve(pTry(fallback));
```
Comment (sindresorhus) [inline index.js]: Don't really need a new dependency for this. Just do:

```js
try {
	resolve(fallback());
} catch (err) {
	reject(err);
}
```

**Comment by sindresorhus** [comment]
Thanks :)
